# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = "https://adney11.github.io/blog/"
theme = 'ananke'

# Copyright and Language
copyright = "Copyright © 2023, Adney Cardoza."
languageCode = "en-US"

Paginate = 5
relativeURLs = true

# Basic metadata configuration for your blog.
title = "adney11"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

SectionPagesMenu = "main"

[languages]
  [languages.en]
   title = "adney11"
   weight = 1
   contentDir = "content"

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
# disableKinds = ["taxonomy"]
# ignoreErrors = ["error-disable-taxonomy"]

[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"

[author]
  name  = "Adney Cardoza"

[permalinks]
  blog = "/:year/:month/:day/:slug"
  library = "/paper/:slug"
  tags = "/tag/:slug"

[sitemap]
 changefreq = "monthly"
 filename = "sitemap.xml"

[params]
  description = "Adney's attempt to being a better public writer"
#  mainSections = ["posts", "blog"]
  background_color_class = "bg-black"
  favicon = "favicon.ico"
  email = "adney11@utexas.edu"
#  site_logo = "img/logo.svg"
  title = "adney11"
  hideMadeWithLine = true

  # By default, this theme displays dates with a format like "02 Jan, 2006", but
  # you can customize it by setting the `dateFormat` param in your site's config
  # file. See [Hugo's Format function docs](https://gohugo.io/functions/format/)
  # for details. An example TOML config that uses [ISO
  # 8601](https://en.wikipedia.org/wiki/ISO_8601) format:
#  dateFormat = "2006-01-02"
#  read_more_copy =  "Read more here"